# Generated by Django 4.2.4 on 2023-08-05 15:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="comment",
            unique_together=set(),
        ),
    ]
