# Generated by Django 4.2 on 2023-08-07 11:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0006_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Images'),
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user', 'game')},
        ),
    ]
